### ISSUE TITLE
Make compatible with yfinance API

### ISSUE THREAD

**Issue by matheusft** [jwergieluk/openfigi#3]
Is there any way to convert the [_exchCode_](https://www.openfigi.com/api/enumValues/v3/exchCode) to the market suffix [used by the **Yahoo Finance API**](https://help.yahoo.com/kb/exchanges-data-providers-yahoo-finance-sln2310.html)?

OpenFIGI identifies, for example, the London Stock Exchange market as  _exchCode_ =  **LN**. However, in order to use Yahoo Finance API you need to add **.L** to the ticker for this same market.

**Comment by jwergieluk** [comment]
No Yahoo support, sorry!
